
language: haskell

sudo: false
cache:
  directories:
    - $HOME/.stack/

branches:
  only:
    - source

env:
  global:
    - GH_NAME="335g.travis"
    - secure: "2Wj10L3jSiiecQDiPTVkdGEdSDLXdauumA5hpQ8QxxgW/ueSvbDabINaINrF65WJqEhBNHV9okSbz66g96wlUK+XELTT9RRrCvrzmSTxzL8mfbJrAqQ5NNHKdjFSmi8s0KmTvceVRAsT5LLfSq/ZzHsPVCQfOyC/JHu14rdiowRERVU3Sffn20N0nhrDohLpeEF1sqpuAyh6i12niJx5KBc+4RE2La5JqYoO+NftUzdkf4wej7UO/MqpytfNcTdS90+wuIFfWe/u2K57QicNt13wIDlkuLdyzbnsIr3Lm/I3+QPQ7f7vGmDgsnCGJ4ba+oU7cIr/Y8ABJ81S1R7jHCqp+AdTpA/wklOSlEyN1AKoZ0nWXhkxbY7AmPSf2H8v39z2jSdEZnvF3YQVKW9UQWfhcebcWNznh16LIdXetjG94cA6WFA8+01AM8vT71w8jpnnls9FgwJsSLv7es2waxRrwv73C0dw3dCdc+kDBFzeYVSVP1iOS3rbDTHn0UhEwXd+riBk1n7pI94CfKM/++9UiCEhYfnKBpxSoxMMXX/jy/fjIDH8/vrW0jysB7bvB3yFEAKTkakqFS7lwEjeJ1Lyxd5koCK2IDF9uHIO/qra7nXv3mDQzpzvSsQAFaMHp7IndFJ26KkEHmw+mhnq/sLWgS44erjRO2gWSOWWcF4=" # token
    - secure: "0qIA6PuKLTh2lrTHICknwUgiuiBEwgyZUy8zGMhuF1SIcFtnHmnAXMpO9rYTJFtkr6PyGGc0IB2xrF9P2GsC7f3TEmqyRZVOjR9HNB2h32QxwD/rVGcVudFzYR2/YGBt5ogSI9CL+RP364OqXubd94N0Q7SUaB6CTWVd0XBr5WtTZG4DiTTNeaX1EVhe5ACWIEsxCV1TMngP1nqfgdAutGER3GtJ722a+dWQ+DLJ8rzdYkW6Jp7IFkUY+SaFd5ndrv5qGsHGrAO4N9HSweqJqZqpulOeOJ+0v2kApGJNIGYosP8JWMeTyt0n7VZ4Q1hVWGpePvX33iV2Zk1heBjQMQpWsHEvMOcrW5v7qsBaZEpRBf5OdM/74ruWglelvk5dCJZLYYVDSAfGYn9eJZeoqC66ZSn8SLn1F2kTfnmXwtQ09X/VuH8VWu1vE1eONqtC7R17l2q4X546s9bFzOQY+2wVrZpjIKV9l8KElAMv57hzJcQgJbgw8YFkFFG9ylfoNpjOePWJInx3WO/RQrvX8eOuc7mrcLoFpklQF3DZXhb80YRRIDO2MGrRMkSx5GWmJnJa5PkNjpvGPRDfJArbnfjBZvLnl6LIeo4L0hsQQrgZIyB2maszB7v/S7w8+rqwnGHG6vSmPCrn5A/69N6neJWvuEGLQMP/qxCK+KPp66I=" # email

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - export PATH=~/opt/ghc/7.8.4/bin:$PATH
  - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

before_script:
  - git config --global user.name "$GH_NAME"
  - git config --global user.email "$GH_EMAIL"

script:
  - stack build --no-terminal
  - cd weblog
  - stack ghc site.hs
  - ./site build
                                                                              
after_success:
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_TOKEN}@${REMOTE}
  - cd _site
  - git add ./*
  - git status
  - git commit -m "Built by Travis (build $TRAVIS_BUILD_NUMBER)"
  - git push --quiet github master:master

notifications: 
  email: false
